[package]
name = "graphql-sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version ="4.0", features = ["dataloader"] }
serde = "1.0.147"
rust-web-example = { path = "../" }
